### ISSUE TITLE
Uitbreiden inschrijfformulieren met meer form-types

### ISSUE THREAD

**Issue by wouterbles** [esac-ic/esac.nl#10]
De inschrijfformulieren kunnen uitgebreid worden met wat meer form types, zoals:

Radio button
Select box
Meteen ook omzetten van jquery -> vue.

**Comment by indiePeeters** [comment]
Kan deze issue wat omhoog in prioriteit? afgelopen weekend hadden we wat problemen met verzekeringen/klimjaarkaart omdat een aantal personen de checkbox in de weekend inschrijfform overzien hadden. Een radio button zou dit oplossen

**Comment by indiePeeters** [comment]
Als de radio button een verplicht veld is moet je een optie kiezen voordat je je inschrijving door kan laten gaan. Hierdoor lezen de deelnemers altijd of ze een klimjaarkaart/verzekering nodig hebben.
