### ISSUE TITLE
Blokkeer Universiteit mail adressen bij inschrijving

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#101]
Verschillende personen schrijven zich in met hun uni email adres. Het nadeel van deze adressen is dat na hun studie ze geen emails meer ontvangen. Uni adressen moeten daarom niet geaccepteerd worden en er zou dus met een persoonlijk email adres ingeschreven moeten worden

**Comment by indiePeeters** [comment]
High prio ivm lente inro

**Comment by wouterbles** [comment]
Wat doen we met de mensen die al ingeschreven staan met hun studie mail?

**Comment by indiePeeters** [comment]
We kunnen naar personen met een uni account die een lidmaatschap hebben een mail sturen met het verzoek dat ze hun emailadress aanpassen, voor reunisten is dit lastiger aangezien we niet weten of de emails ontvangen worden.
