### ISSUE TITLE
Instucteurs toegang geven tot geboortedatum leden

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#107]
Instructeurs hebben de geboortedatum van leden nodig om een certificaat aan te vragen bij de NKBV.

**Comment by wouterbles** [comment]
Dit lijkt niet meer erg noodzakelijk na overleg met robby. Om een pasje aan te vragen bij de NKBV is ook het NKBV nummer van de klimmer nodig en die slaan we niet meer op in het ledensysteem. Voor aanvraag van de pasjes moet er dus toch al aan de klimmers het nummer gevraagd worden, dan kan net zo goed ook de geboortedatum gevraagd worden.

**Comment by indiePeeters** [comment]
Mee eens! Dan kan deze gesloten worden
