### ISSUE TITLE
Killswitch

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#109]
Het bestuur heeft besloten om een killswitch in de website te bouwen. Deze kan geactiveerd worden via de beheer functie

Wanneer deze actief is word er nog maar een pagina weergeven. Deze pagina legt uit wat de ESAC is en laat het nummer van de voorzitter zien. 

Het lijkt me handig dat inloggen nog wel mogelijk is. zodat via de beheer functie de killswitch weer ongedaan gemaakt kan worden. 

Wat denken jullie hierover?

**Comment by indiePeeters** [comment]
High prio omdat dit voor de zomer gefixt moet zijn

**Comment by wouterbles** [comment]
Lijkt me opzich een prima toevoeging, maar "moet voor de zomer" lijkt me een beetje overdreven. De ESAC doet al meer dan 20 jaar zonder.

**Comment by indiePeeters** [comment]
Oke dan zie het als het zou erg fijn zijn als dit voor de zomer gefixt kan zijn ;)

**Comment by wouterbles** [comment]
Volgens mij is dit makkelijk op te lossen door een setting toe te voegen in de table en vervolgens even iets in de frondendcontroller aanpassen dat alles redirect naar een bepaalde view als die setting aan staat.

**Comment by otherwise777** [comment]
Ik heb deze discussie eerder voorbij zien komen,
Toen ik ooit de aanvraag heb ontvangen ging dit over beeld materiaal, dus foto's. Niet over de hele website. 

Deze vraag komt niet direct uit het bestuur maar vanuit de NSAC geloof ik? Wat is precies hun advies? Zei hebben hier meer ervaring mee omdat ze in het geval dat er iets gebeurd met een SAC ook direct betrokken zijn ivm media

**Comment by wouterbles** [comment]
In de noodprocedure heeft de nsac het erover dat de hele site op zwart moet, zodat ook informatie over commissieleden etc. niet uitlekt. Lijkt me dus wel de moeite waard om te implementeren.

**Comment by otherwise777** [comment]
> In de noodprocedure heeft de nsac het erover dat de hele site op zwart moet, zodat ook informatie over commissieleden etc. niet uitlekt. Lijkt me dus wel de moeite waard om te implementeren.

Alright, prima
