### ISSUE TITLE
Hernoemen van "klimactiviteit" checkbox naar "laat certificaten zien in agenda item"

### ISSUE THREAD

**Issue by wouterbles** [esac-ic/esac.nl#141]
De functie van de knop was niet duidelijk, kreeg er al van een aantal mensen uit het bestuur vragen over. Dit beschrijft beter het resultaat van de checkbox.

**Comment by indiePeeters** [comment]
Wat ik ook merkte, is dat de checkbox altijd aangevinkt staat als je een agenda item edit. Ook al stond deze eerst uit. hierdoor passen mensen dit soms aan zonder dat ze het door hebben
