### ISSUE TITLE
Verengingszaken onzichtbaar maken voor niet leden

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#149]
De verenigingsbestanden moeten onzichtbaar gemaakt worden voor niet leden. Dit gaat vooral om ALV Stukken, omdat hier ook namen in benoemd worden. 

Volgensmij moeten de volgende bestanden publiek zijn:
- Statuten
- Privacy Policy 

De rest zal dus enkel weergeven moeten worden als er ingelogd is.

**Comment by wouterbles** [comment]
Waarom moet dit een IC dingetje zijn? Dit is toch een kwestie van vinkje "login nodig" aanzetten in de website?

**Comment by indiePeeters** [comment]
Dan zijn de statuten en privacy policy toch niet meer zichtbaar? Ik denk dat de mooiste oplossing is om de verenigingszaken pagina wel publiek te houden, maar meer content te weergeven wanneer er ingelogd is.

**Comment by wouterbles** [comment]
Persoonlijk vind ik het geen mooie oplossing om bepaalde content op een website te verbergen. Dan kan de pagina namelijk niet meer aangepast worden in de back-end.

**Comment by wouterbles** [comment]
Voor zover ik weet is het niet verplicht om die bestanden openbaar op de website te hebben staan. Iedereen kan ze als het goed is toch al opvragen bij de KVK.

**Comment by indiePeeters** [comment]
hmm, wat lijkt je dan de beste oplossing? twee aparte pagina's vind ik ook niet echt handig

**Comment by indiePeeters** [comment]
De privacy policy is te vinden als je lid wordt, Wanneer de statuten gewijzigd zijn is het van belang dat deze bij de kvk liggen. Dit is dus niet nodig
