### ISSUE TITLE
Opzetten GSuite: Teamdrive

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#150]

**Comment by wouterbles** [comment]
Is het nuttig om hier een github issue van te maken? Is namelijk niet gelinkt aan de website zelf toch?

**Comment by indiePeeters** [comment]
meer voor me zelf, lekker scrummen :)

**Comment by indiePeeters** [comment]
Ik heb even met Gsuite zitten spelen,  het is mogelijk om groepen aan te maken (deze groepen krijgen een mailadres bijvoorbeeld 43@esac.nl) vervolgens kunnen hier personen aan gekoppeld worden met persoonlijke email adressen, deze groepen kunnen vervolgens toegang krijgen tot een drive.
Voor nu is het plan om voor elke commissie een aparte drive te maken ipv een folder.

Mij lijkt dit een goede oplossing voor drive. Wat vinden jullie?

**Comment by wouterbles** [comment]
Klinkt als een goed idee, hoe zit het met opslagruimte enzo? We kunnen er nog wel een keer naar kijken op de uni?

**Comment by indiePeeters** [comment]
Volgens [deze](https://support.google.com/a/answer/7338880?hl=en) link is er geen limiet aan storage, alleen aan het aantal bestanden dat in een teamdrive zitten.

**Comment by indiePeeters** [comment]
Voor nu zouden we eerst moeten kijken naar de mail mogelijkheden binnen Gsuite (als we dit uberhaupt willen), Indien we dit willen zou het domein omgezet moeten worden naar esac.nl, Als we enkel drive willen gebruiken zou er een ander domein moeten komen.

**Comment by wouterbles** [comment]
Het is dus niet mogelijk om enkel gsuite drive te gebruiker zonder dat je de mail DNS records instelde? Of wat is de reden dat we een tweede domein nodig hebben als we geen gsuite gmail gaan gebruiken?

**Comment by indiePeeters** [comment]
Voor GSuite heb je altijd een domein nodig, Volgens [deze](https://support.google.com/a/answer/183895?hl=en) en [deze](https://support.google.com/a/answer/60216?hl=en) link kan dat enkel door je DNS records aan te passen. Als we Gsuite willen gebruiken in combinatie met mailgun/mailman zouden we dus een tweede domein nodig hebben. Misschien werkt een subdomein zoals drive.esac.nl?

**Comment by wouterbles** [comment]
Maar DNS records aanpassen betekent niet perse dat mailgun niet meer werkt, het hangt er vanaf welke DNS records aangepast moeten worden.

**Comment by indiePeeters** [comment]
Ik begreep eerst dat dit niet mogelijk was, Het gaat om het toevoegen van een verfication record die je van Gsuite krijgt.

**Comment by wouterbles** [comment]
Dat is geen enkel probleem, dan blijft mail gewoon werken.

**Comment by indiePeeters** [comment]
Oke, maar om daarna over te stappen naar mail is dan wel lastiger, klopt? In dit geval eerst kijken of we Gsuite voor mail willen gebruiken.

**Comment by wouterbles** [comment]
Lijkt me inderdaad een goed idee om eerst te kijken of we gsuite mail willen gebruiken. Want als we nu gsuite Drive opzetten met esac.nl kunnen we niet de mail functionaliteit van gsuite testen zonder dat mailgun stopt met werken. Dus voorlopig even gsuite mail testen onder het testdomein (Wouter les.com)

**Comment by indiePeeters** [comment]
#155

**Comment by indiePeeters** [comment]
Bekijken of het mogelijk is om dit om te zetten naar esac domein, @wouterbles keertje samen doen in meta

**Comment by indiePeeters** [comment]
GSuite is opgezet en ik ben momenteel het bestuur aan het overzetten. Er zijn nu nog een aantal dingen die moeten gebeuren:

1. De ESAC public folder moet beschikbaar zijn buiten GSuite members
2. Er moet een instructiedocumentje komen hoe commissieleden Teamdrives moeten gebruiken
3. De commissies moeten toegevoegd worden aan de GSuite en bestanden moeten overgezet worden

**Comment by wouterbles** [comment]
Gefixt toch?
