### ISSUE TITLE
Nieuwsbericht auteur veld is verdwenen

### ISSUE THREAD

**Issue by wouterbles** [esac-ic/esac.nl#156]
Na het uitschakelen van Vue in de beheeromgeving is de bug ontstaan dat het nieuwsbericht auteursveld in beheer niet meer zichtbaar is.

**Comment by nieka** [comment]
Dit komt doordat dat ook een vue element is

**Comment by wouterbles** [comment]
Ja klopt, is denk ik makkelijk te fixen door wel ff een div id=app op de nieuwsitem edit pagina te zetten.

**Comment by nieka** [comment]
Ben ik momenteel al mee bezig
