### ISSUE TITLE
Mail zelf implementeren

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#178]
Dit issue is even voor discussie, @wouterbles had het idee om de mail functionaliteit zelf te bouwen aangezien we eigenlijk iets redelijks simpels willen. 

We konden Amazon SES hiervoor gebruiken maar dit zou wat te duur worden.
Ik denk dat het een groot voordeel is om de lijsten zelf bij te houden. Dit maakt het up to date houden van deze lijsten een stuk makkelijker. Daarnaast zouden we dan enkel het versturen/ ontvangen moeten uitbesteden

Wat vinden jullie hiervan? Welke opties hebben we? Wat is de voordeligste opties en welke optie is in het gevolg het handigst indien we van mail server wisselen?

**Comment by otherwise777** [comment]
Waar gaat dit precies over? Welk deel van de mail?

**Comment by indiePeeters** [comment]
@wouterbles kan hier wel meer over kwijt.
