### ISSUE TITLE
Deprecated Code veroorzaakt error bij het exporteren van inschrijvingen

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#196]
Wanneer er inschrijvingen gexporteerd worden gaat het fout, volgens de logs wordt dit door deprecated code veroorzaakt 
![Capture](https://user-images.githubusercontent.com/16254233/72060608-a0c5e200-32d4-11ea-8a08-324662430fae.PNG)

Steps to reproduce:
Exporteer de inschrijvingen van WEBI 2020 agenda item.

**Comment by otherwise777** [comment]
dit heeft met de excel module te maken denk ik, exporteren van leden lukt ook niet meer

**Comment by otherwise777** [comment]
Ik heb de vorige versie terug gezet op de productie server, exporteren van leden werkt weer

**Comment by otherwise777** [comment]
hmm, ik denk dat dit een php 7.4 dingetje is, en dat we onze libraries moeten updaten

**Comment by wouterbles** [comment]
Dit lijkt gefixt!
