### ISSUE TITLE
db migratie optie voor docker

### ISSUE THREAD

**Issue by otherwise777** [esac-ic/esac.nl#199]
op dit moment word er geen migratie uitgevoerd bij een nieuwe docker image. Dit kan verholpen worden door dit in een startup script te zetten maar we moeten ook nadenken over een rollback mechanisme. 

Hebben we een ooit een rollback moeten doen waarbij de database een rollback kreeg?En dan bedoel ik een rollback op tables, niet op data

**Comment by wouterbles** [comment]
> Hebben we een ooit een rollback moeten doen waarbij de database een rollback kreeg?En dan bedoel ik een rollback op tables, niet op data

We hebben nog nooit rollbacks gedaan, dus dat kan ik niet met zekerheid zeggen eigenlijk. Rollbacks en migraties gaan niet heel erg hand in hand, zou er voor nu dus niet al te veel rekening mee houden.

**Comment by otherwise777** [comment]
> > Hebben we een ooit een rollback moeten doen waarbij de database een rollback kreeg?En dan bedoel ik een rollback op tables, niet op data
> 
> We hebben nog nooit rollbacks gedaan, dus dat kan ik niet met zekerheid zeggen eigenlijk. Rollbacks en migraties gaan niet heel erg hand in hand, zou er voor nu dus niet al te veel rekening mee houden.

Volgens mij gaan die wel hand in hand, als je een migratie schrijft in het project schrijf je een up() en down(), de up() gebruik  je bij een "migrate" en de down() gebruik je bij een "downgrade". Ik zie wel dat de down() niet altijd gemaakt is in de laatste migraties

Maar, om realiistisch te blijven, down() is nog nooit gebruikt op productie, dus laten we alleen een migratie functie maken en als het mis gaat de hele database een rollback geven indien nodig? 

Vaak is de down() niet nodig, als je bijvoorbeeld een column toevoegt dan is dat bijna altijd backwards compatible, maar columns aanpassen bijvoorbeeld niet.

**Comment by wouterbles** [comment]
Ben het met je eens, gewoon altijd een migrate draaien als de docker image geupdate wordt.

**Comment by otherwise777** [comment]
Done in laatste merge
