### ISSUE TITLE
Beheer vanuit OC

### ISSUE THREAD

**Issue by Matco42** [esac-ic/esac.nl#21]
Ivm AVG is het niet wenselijk dat de OC alle gegevens van leden kan zien en aan kan passen, zij moeten echter wel beheerder zijn om de klimstatussen aan te kunnen passen. Daarom een rol status beheerder toevoegen die bij leden gegevens basisgegevens kan zien en alleen de klimstatus aan kan passen.

**Comment by aralon** [comment]
Heb hiervoor een pull-request geopend, #23
