### ISSUE TITLE
Automatisch verwijderen van backups na een bepaalde tijd

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#236]
Afgelopen keer is het geheugen van de server vol gelopen, dit komt doordat we veel backups opgeslagen worden, na een bepaalde tijd of na een bepaald aantal backups moeten de oudere backups verwijderd worden om ruimte vrij te maken

**Comment by kalkoen** [comment]
@indiePeeters Weet je of dit met de vernieuwde deployment opgelost is?

**Comment by wouterbles** [comment]
@indiePeeters dit is gefixt toch?

**Comment by marijnvanderhorst** [comment]
> @indiePeeters dit is gefixt toch?

Is zo te zien gefixt inderdaad. Alle backups ouder dan 14 dagen zouden verwijderd moeten worden, en de laatste backup is van 11 september.

**Comment by indiePeeters** [comment]
Klopt, is opgelost.
