### ISSUE TITLE
Fix members not staying signed in

### ISSUE THREAD

**Issue by MartijnKraakman** [esac-ic/esac.nl#278]
Have to sign in again sometimes after ending a session (i.e. closing browser, restarting phone)
- Have gotten one report of this happening, and have experienced it myself.
- Has been happening since ~June 2022.
- Maybe be related to recent back-end updates?

**Comment by marijnvanderhorst** [comment]
@MartijnKraakman Are sessions ended only after a new release is deployed to https://esac.nl? Or does it also occur while the same version is running, without any deployments in the meantime?

**Comment by wouterbles** [comment]
It's only an issue for me when a new release is deployed.
