### ISSUE TITLE
Enlarge Management buttons 

### ISSUE THREAD

**Issue by MartijnKraakman** [esac-ic/esac.nl#281]
![image](https://user-images.githubusercontent.com/100088405/173321695-46587aae-3fcf-4cdb-9cec-86213cf25191.png)
- These buttons are really small, and it wouldn't be the first time someone accidentally clicks the wrong one. 
- Making them bigger would prevent this issue

**Comment by kalkoen** [comment]
@indiePeeters Perhaps create a pull request? Or is this enhancement not done yet?

**Comment by indiePeeters** [comment]
Fixed in #299
