### ISSUE TITLE
Fix stuff not showing in english in the agenda

### ISSUE THREAD

**Issue by ThijsEgberts** [esac-ic/esac.nl#310]
In the agenda page some stuff is hardcoded to dutch.
![afbeelding](https://user-images.githubusercontent.com/104772243/209687798-70595f48-0e67-423a-b625-5b6adc876820.png)
The agenda stuff is in the vue folder in resources.

**Comment by ThijsEgberts** [comment]
probably because of the way vue is loaded in the agenda, the target language is not yet loaded when the agenda data is passed to vue so therefore the content in the actual agenda items are not being translated

**Comment by wouterbles** [comment]
Fixed when switching to english.
