### ISSUE TITLE
add: template agenda items

### ISSUE THREAD

**Issue by ThijsEgberts** [esac-ic/esac.nl#321]
I thought it might be nice to make a way to more easily make agenda items that have to be made often, like the Monday trainings

**Comment by wouterbles** [comment]
What would be the advantage/disadvantage over copying the agenda items as is currently possible?

**Comment by ThijsEgberts** [comment]
I saw elena copying the agenda items and I asked her if she thinks it would be nice to be able to add template agenda items, and she said that would be really nice since it would make adding the repeating agenda items way less tedious

**Comment by ThijsEgberts** [comment]
I thought of it more as a template so that creating the often used agenda items is more like, add new agenda item -> select the template -> set the date but maybe we can ask some secretaries what they think would be nice
