### ISSUE TITLE
Vindbaarheid Stuntteam

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#44]
De pagina van het stuntteam is niet goed vindbaar op google. eigenlijk willen we dat deze pagina minstens met zoektermen "bedrijfsuitje klimmen Eindhoven" of "stunt klimmen eindhoven" moet de pagina in de eerste zoekresultaten komen. Dit kan de aantal stunts zeker bevorderen.

**Comment by otherwise777** [comment]
Dit is niet zo maar gedaan, er kunnen wel wat basic meta tags toegevoegd worden, maar uiteindelijk is een belangrijke factor hoeveel mensen de website bezoeken als ze daar naar op zoek zijn. Google werkt ook steeds minder met deze tags. wellicht dat het ook helpt om een robots.txt toe te voegen

**Comment by wouterbles** [comment]
Ja, mee eens. Je zou de tekst op de pagina wat kunnen herschrijven zodat de worden/zinnen die je hierboven noemt in de tekst staan. Meer kan je naar mijn idee niet doen. Wat zeker zou helpen is een aparte website voor de stunt commissie, maar ik vraag me af of we dat willen.

Oh en trouwens, wil de commissie zelf ook meer stunts?

**Comment by wouterbles** [comment]
Wat willen we hier nog mee doen? Naar mijn idee kunnen we er als IC weinig mee.
