### ISSUE TITLE
Beheer: toevoegen nieuwsberichten autofill auteur veld

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#45]
Bij het toevoegen van nieuwsberichten is het makkelijker dat er een autofill bij het auteur veld komt. zo weet je dat je zeker dat je de naam ook goed spelt.

**Comment by wouterbles** [comment]
Een vinkje klimactiviteit toevoegen aan het agenda item, niet per categorie want categorien zijn dynamisch!
