### ISSUE TITLE
photoalbum photoviewer gaat niet naar volgende pagina

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#60]

**Comment by wouterbles** [comment]
Oplossing voor dit probleem: pagina navigatie moet naar de front-end ipv server-side. Het lijkt me de beste oplossing om dit dan met Vue te doen, maar daar heb ik geen verstand van. @marijnvanderhorst @nieka ?

**Comment by indiePeeters** [comment]
pagination eruit slopen
