### ISSUE TITLE
photoalbums check thumbnail and image size

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#61]

**Comment by indiePeeters** [comment]
moeten ongeveeer 30kb zijn

**Comment by wouterbles** [comment]
Voordat we photoalbums echt kunnen gebruiken lijkt het me noodzakelijk om de thumbnail en afbeelding grootte consistent te hebben. Anders uploaden we straks afbeeldingen met een te grote filesize naar b2.

**Comment by indiePeeters** [comment]
Ik heb de thumbnails nu terug getrokken naar 15kb. De images zelf die orgineel 8mb zijn worden nu rond de 1.2 mb, over het tweede twijfel ik of dit klein genoeg is

**Comment by wouterbles** [comment]
Thumbnails lijken me prima zo! 1.2 MB is best veel, maar ik snap dat je natuurlijk de kwaliteit niet echt omlaag kan zetten omdat kleinere afbeeldingen dan weer slechter worden. Idealiter zou het verkleinen op een slimmere manier gebeuren en het altijd rond een bepaalde bestandsgrootte brengen. Dat lijkt me alleen erg ingewikkeld te ontwikkelen.
