### ISSUE TITLE
Tim leert Laravel!

### ISSUE THREAD

**Issue by wouterbles** [esac-ic/esac.nl#62]
Tim heeft goede voornemens. Tim gaat deze keer echt Laravel leren. Echt! Als hij het deze keer niet doet wordt hij uit de IC gezet. Tim wil graag in de IC blijven.

**Comment by indiePeeters** [comment]
#63

**Comment by indiePeeters** [comment]
Succes :) 🥇

**Comment by otherwise777** [comment]
Kunnen we hier op inleggen? Dit was al een ding toen de nieuwe website werd gemaakt :)

**Comment by wouterbles** [comment]
Vgm staat alles al in #63, dus ik sluit hem ;)
