### ISSUE TITLE
Google calendar beschikbaar maken voor leden 

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#64]
1. zorgen dat leden in de agenda kunnen
2. als het gebruikt word dit synchroniseren met de agenda op website

**Comment by otherwise777** [comment]
Welke kant wil je het op synchroniseren? Van google agenda naar de website of andersom? 
Is het idee om een .ics file te maken van de agenda op de website die mensen dan kunnen importeren in hun eigen google agenda? Dit heb ik eerder gemaakt en is goed te doen, het enige lastige is dat elke agenda (google/outlook/apple) zijn eigen manier heeft van updaten en ICS protocol interpretatie

**Comment by indiePeeters** [comment]
De bedoeling is om het van website naar google agenda te doen. Dus wanneer er een agenda item op de website gemaakt wordt dit gesynchroniseerd wordt naar de google agenda. Het zou tof zijn als dit met elke agenda zou werken.

**Comment by otherwise777** [comment]
dat is goed te doen, het werkt als volgt:
We maken een endpoint aan die een .ics file genereert van alle agenda items. Agenda systemen pollen dat endpoint om de zoveel tijd . (hangt af van mail systeem, outlook doet het wanneer je outlook opent, google cached het elke 12 uur) dus op het moment dat een agenda tool het endpoint aanroept heeft die altijd de laatste versie van de hele agenda. 
Het werkt niet zo dat je elk item opnieuw in de google agenda stopt, je stuurt in 1 keer de hele agenda met alle items naar de client toe, die zet dat om in alle agenda items

**Comment by otherwise777** [comment]
Ik ga hier binnenkort verder aan knutselen, ik koppel hem aan de agendacontroller

**Comment by indiePeeters** [comment]
Aangezien het 43ste bestuur dit snel wilt hebben, ben ik nu een nieuwe google agenda aan het maken. Ik ga de publieke share link onder een knopje op de agenda pagina zetten zodat mensen deze vast kunnen toevoegen aan hun agenda. voor nu is dus de bedoel dat commissieleden hun agenda zaken in beide agendas zetten totdat dit af is.

**Comment by indiePeeters** [comment]
Nog een puntje.

we krijgen dadelijk dus twee google agendas:

Eentje voor commissies (met voorlopige datums en vergaderingen)
Eentje voor leden (definitieve datums )

De bedoeling is dadelijk we dat de website agenda synchroniseert met beide agendas

**Comment by wouterbles** [comment]
Waarom zou je niet gewoon een voor activiteiten en een voor de commissies doen? Dat is denk ik makkelijker te implementeren.

**Comment by otherwise777** [comment]
> Nog een puntje.
> 
> we krijgen dadelijk dus twee google agendas:
> 
> Eentje voor commissies (met voorlopige datums en vergaderingen)
> Eentje voor leden (definitieve datums )
> 
> De bedoeling is dadelijk wel dat de website agenda synchroniseert met beide agendas

Hoe werkt dit straks op de website? hebben we beide functionaliteiten in de huidige agenda? voorlopig/definitieve activiteit

**Comment by wouterbles** [comment]
Nee, het plan is dat commissieleden in de tweede agenda zelf via Google Calendar agenda items toe kunnen voegen. Alleen is dat naar mijn idee niet mogelijk, omdat de kalender op de ESAC server staat om het zo maar te zeggen en dus read-only is.

**Comment by indiePeeters** [comment]
> De bedoeling is dadelijk wel dat de website agenda synchroniseert met beide agendas

Oke, ik had het even verkeerd begrepen :) 

De bedoeling is dat enkel de leden agenda gesynchroniseerd wordt van website naar agenda. 

De commissieagenda wordt gebruikt voor vergaderingen en het reserveren van datums. Deze hoeft dus niet gesynchroniseerd te worden.

**Comment by wouterbles** [comment]
Top! In dat geval is dit volgens mij een erg makkelijke feature.
