### ISSUE TITLE
Uitzoeken hoe Ideal betalingen makkelijk in de boekhouding verwerkt kunnen worden

### ISSUE THREAD

**Issue by indiePeeters** [esac-ic/esac.nl#67]

**Comment by otherwise777** [comment]
Zoals ik al aangaf, gebruik Mollie : ) scheelt veel ellende

**Comment by wouterbles** [comment]
Het schijnt nogal moeilijk te zijn om betalingen die met mollie gedaan zijn in de boekhouding van de ESAC te verwerken (unit mulitvers). We moeten even bij de penno vragen of dat inmiddels goed kan voordat we ideal betalingen implementeren.

**Comment by wouterbles** [comment]
Is dit inmiddels besproken met Thijs/Jan/Ralph?

**Comment by indiePeeters** [comment]
Nog niet in detail, Ralph zag niet een erg groot probleem. Aanstaande maandag heb ik het hierover met Ralph en Thijs.

**Comment by indiePeeters** [comment]
Ralph heeft mij uitgelegd dat het mogelijk moet zijn met de mt940 bestanden van de transacties te downloaden vanaf mollie. Deze bestanden moeten een duidelijk beschrijving bevatten van de transactie zodat deze correct gematched kunnen worden in de boekhouding, misschien is een string identifier hier handig voor. Het lijkt me ook handig (indien het mogelijk is) het downloaden van deze bestanden vanaf de website te laten verlopen. Zodat er geen extra systeem(mollie) is waar de penno in zou moeten loggen. 

We kunnen dus best beginnen te implementeren, maar zouden later even moeten kijken wat handig is voor het matchen van transacties en activiteiten.

**Comment by wouterbles** [comment]
Duidelijk! Goed dat je dit hebt uitgezocht.

Op di 14 mei 2019 10:53 schreef indiePeeters <notifications@github.com>:
