### ISSUE TITLE
Foto albums toevoegen

### ISSUE THREAD

**Issue by wouterbles** [esac-ic/esac.nl#7]
Zelf bouwen met behulp van AWS s3

AWS S3 heeft natuurlijk niet de mogelijkheid om on the fly afbeeldingen te resizen, we moeten dus van elke geuploade afbeelding twee nieuwe aanmaken:

Kleine thumbnail voor overzicht (200x300 oid)
Grote thumbnail voor detail view (1080p oid)
Origineel voor download knopje
Dat zou gewoon met de laravel image library kunnen die we nu al gebruiken, geen idee hoeveel rekenkracht het zou kosten om dit voor heel veel grote afbeeldingen te doen?

Heb al een API key aangemaakt voor een S3 instance, laat maar weten als je die wil hebben @indiePeeters

**Comment by indiePeeters** [comment]
#28
