### ISSUE TITLE
Docker in productie

### ISSUE THREAD

**Issue by otherwise777** [esac-ic/esac.nl#71]
**Wat will we**: Docker in productie!
**Wanneer willen we dat**? Nu!
Oke even wachten

Hier is uitgelegd hoe het voorstel in elkaar zit om met docker naar productie te gaan, het uitgangspunt is:

- na elke push naar master word een docker image gebuild
- na elke build word deze automatisch deployed op de website
- alle docker images zijn publiekelijk toegankelijk

De nadruk van dit voorstel ligt op usability en security. Alles moet veilig en simpel zijn. we maken hierbij gebruik van bestaande tools: Github/Travis met als toevoeging [docker hub](https://hub.docker.com/orgs/esac).

Travis word uitgebreid met een docker build en deployment, in de travis-ci.yml komt een secret waarmee travis een deployment script kan afvuren op de server ([link](https://kjaer.io/travis/)) en vervolgens word er een nieuwe docker container gerund op de server.
Dit deployment script kan ook op de git geplaatst worden, het enige wat die doet is de environment file attachen en een docker run command uitvoeren op het image dat zojuist gebouwd is.

Security docker hub, we hebben een esac organisatie, waarbij iedereen images kan pullen maar er zijn maar een paar mensen die kunnen pushen, dit zijn dezelfde mensen die toegang hebben op de server zelf + een account voor travis zodat travis kan pushen naar de repo.

Denk even na over het "publiekelijk" stuk, op dit moment staat onze git niet online, dit kan dus impact hebben. Dockerhub laat echter geen gratis repo's op prive staan.

-------------------- Oude voorstel --------------------
Toen ik aan het knutselen was met de docker omgeving van de website voor development, (met als use case het makkelijk maken voor nieuwe ontwikkelaars om te beginnen met ontwikkelen) dacht ik dat het handig kon zijn om ook een docker image van de website te draaien in productie. Dit zou gaan om een andere manier dan hoe we dit nu in ontwikkeling gebruiken.

Dit is meer een discussie onderwerp, het heeft veel impact en ik heb niet alles uitgedacht, voel je vrij om lekker mee te denken :D 

Wat extra informatie:
**Wat zou er in een container draaien**
Heel simpel gezegd bestaat de website uit 2 delen, de database en de website. Containers zijn ontzettend goed in het beheren van "stateless" omgevingen. Een database is niet stateless dus die zou je hier niet in draaien. De website is stateless op een paar onderdelen na zoals de logs. 

**Hoe runnen we het:**
Er zijn verschillende manieren om containers te runnen, elke methode heeft pro's en cons, ik zet ze even onder elkaar met onze use cases:

- Docker run, het meest basale commando, docker run. Dit is niet gewenst want zodra je container crashed komt hij niet meer terug online. Dit is echter wel vergelijkbaar met hoe het nu draait, er is (voor zover ik weet) niet zoveel gaande om de website terug te krijgen als hij neer gaat
- Docker compose, Iets geavanceerder en word op dit moment in de ontwikkel omgeving gebruikt. je kunt wat dingen instellen zoals wat er gebeurd als containers crashen, het doel van docker compose is voornamelijk testen en niet zo zeer productie, al gebeurd het wel en is het voor onze use case wellicht ook een idee.
- Docker Swarm, de container orchestration optie voor docker, helaas is dit project  een beetje aan het dood bloeden ivm de andere container orchestration opties die  er zijn zoals kubernetes/openshift
- Kubernets/Openshift, dit zijn container orchestration frameworks, deze kunnen letterlijk alles, van security/load balancing, automatische up/down scaling, het is wellicht iets overkill als je denkt dat we een simpele website hosten. 

Ik heb dus niet echt een voorkeur gegeven omdat ik daar nog niet uit ben

**Waarom switchen naar Docker, wat is het voordeel**
De website draait prima zoals die nu draait, dus in principe is het niet nodig, er zijn een paar kleine voordelen die ik nu zie:
- Makkelijk updaten/rollback, In principe maak je een image van elke versie van de website, in deze image zit de hele image (zonder database), en het opstarten van een image duurt gemiddeld minder dan een second. Een rollback word supersimpel door simpelweg de image versie aan te passen, houd er rekening mee dat als je in een nieuwe versie je database wijzigd dat je niet zo maar een rollback uit kan voeren als je vorige versie een bepaalde database nodig heeft.
- Test/productie omgeving in sync, een image is overal hetzelfde, onafhankelijk van OS/frameworks. Als je een image hebt van de productie omgeving dan weet je dat als je test omgeving goed draait het ook zo werkt op de productie omgeving ook zo draait. Op dit moment testen we op een andere omgeving dan onze productie omgeving, dit heet production parity 

**Conclusie**
Dus, leuk discussie onderwerp, ik ga er nog even een maandje over slapen/nadenken en ondertussen duik ik wat verder de productie omgeving in. Vooralsnog is dit een idee, dus geen voorstel om het in productie te draaien, wellicht gaan er nu belletjes rinkelen bij andere die misschien use cases zien die ik iets weet, reageer vooral hierop : )

**Comment by wouterbles** [comment]
Klinkt als een goed idee, scheelt veel werk bij het eventueel overstappen van hosting provider of het herstellen van de website.

**Comment by indiePeeters** [comment]
Even kijken naar laravel arc

**Comment by indiePeeters** [comment]
Docker in combinatie met Travis CI gebruiken.

**Comment by otherwise777** [comment]
ik heb het orginele voorstel aangepast met een soort van ontwerp hoe het in productie kan werken

**Comment by otherwise777** [comment]
tot dusver:
Thomas had een goeie opmerking, dat php artisan serve maar 1 request tegelijk behandeld, dat is niet handig om in productie te draaien.

Het voorstel is om een nginx container ervoor te draaien, mysql blijft voorlopig nog lokaal draaien.

Ik had wat moeite alles aan elkaar te krijgen ivm netwerk. Omdat docker in zijn eigen netwerk draait kan hij niet bij mysql tenzij hij het ip heeft. de oplossing hiervoor is --network="host" daarmee heeft hij dezelfde netwerk config als de container (dit kan bij effecten hebben)

het commando om te runnen: _docker run -it -p 8000:8000 --rm -v $(pwd)/.env:/var/www/.env --name esac_website --network="host" esac/website:0.0.2_

environment file word gemount op runtime, dit moet niet heel veel uitmaken kwa snelheid maar het is een idee om later een loadtest te doen met deze methode, en met een environment file erin gebakken. Dit kan door op de server een image te bouwen met als parent image de huidige build en dan kopieer je de environment file erin. Je hebt dan een image met secrets erin, maar deze staat niet op de repo.

volgende uitdaging: images laden niet en uploaden niet. De directory waar images in staan: public/storage/image_uploads|newsItems is leeg, hier komen de images ook niet in wanneer je images upload, ik heb geen idee waar dit aan ligt en wat de verschillen zijn tussen wat we in de server hebben draaien en lokaal, want lokaal werkt dit ook niet

Dan tot slot, ik zag dat je ook een kubernetes cluster kan kopen bij digitalocean, deze probeer ik ook even uit, wellicht dat dit een goedkoper alternatief is zelfs, om daar een node te halen en dan de website/nginx op te hosten

**Comment by wouterbles** [comment]
Het env file wordt als het goed is gecached, zie https://laravel.com/docs/6.x/configuration#configuration-caching.

Voor die image directory, heb je storage:link gedaan?

Nog iets om rekening mee te houden, voor productie moet er ook letsencrypt een certificaat aanmaken.

**Comment by otherwise777** [comment]
thanks voor alle feedback, ook van @thomas 
Ik heb alles nu werkend, de volgende stap is alles hosten op een eigen droplet instantie en de data overzetten zodat alle functionaliteiten getest kunnen worden.
Hiernaast zal ik een architecture overview maken van hoe de componenten met elkaar samen werken, dit is namelijk niet straight forward, de nginx container en php container delen een volume, wat belangrijk is om de public content snel te delen. de php container schrijft naar het volume, en de nginx container leest van het volume. 

de laatste stap, nadat we weten of alles nog steeds goed werkt, is zorgen dat alles veilig opgezet is @thomas kan hier vast bij helpen. ook staat er nu veel junk in de php container ivm wat workarounds, maar deze gaan er ook nog uit.

**Comment by otherwise777** [comment]
Test setup is klaar: [http://188.166.30.63:8990](http://188.166.30.63:8990) ik heb de /storage en database gekopieerd naar mijn eigen droplet, je kan dus inloggen met je eigen esac.nl gebruikersnaam
TODO:

- [ ] ssl activeren
- [ ] testen?
- [ ] dockerfile optimaliseren (staat veel junk in ivm testing)

Hoe werkt het?
Dit is de structuur van de server:

.
├── .env.prod
├── 20191205_esac_backup.sql
├── docker-compose.yml
└── storage

en de mappen structuur van /storage hier worden alle bestanden in opgeslagen en deze word gemount op de images

└── storage
    ├── app
    │   └── public
    ├── debugbar
    ├── framework
    │   ├── cache
    │   ├── sessions
    │   ├── testing
    │   └── views
    └── logs

bij het opstarten worden de environment variables van de .env.prod file (die in de root staat, niet op git) geladen in de image, hiervoor staat in de dockerfile een config:clear (al die laravel caching heeft me veel hoofdpijn bezorgd) De opzet is heeft alleen "docker-compose up -d" nodig, dan draait het in de background, als je iets aanpast zoals een update van de website hoef je alleen de image opnieuw op te starten, en dit doe je door hetzelfde command te runnen, alles wat niet veranderd is update niet.

**Comment by otherwise777** [comment]
Zowel SSL staat aan en de dockerfiles zijn geoptimaliseerd, dit kan nog beter maar vooralsnog is het even genoeg.
Test server staat online: https://beta.esac.nl
Er is een container toegevoegd, certbot om de certificaten te vernieuwen. Er is wel wat setup nodig om dit op te zetten, ik zit te denken om dit of in onze git te gooien of in een aparte git, heeft iemand hier een mening over? Er komen geen certificaten oid in te zitten, maar het maakt het makkelijker om alles wat we op de server hebben, inclusief configs, op 1 plek te houden.

**Comment by nieka** [comment]
@otherwise777 deze kan denk ik gesloten worden?

**Comment by otherwise777** [comment]
yes
