### ISSUE TITLE
Submenu items niet zichtbaar maken werkt niet

### ISSUE THREAD

**Issue by wouterbles** [esac-ic/esac.nl#76]
Wanneer je bij een sub-menu item het vinkje "zichtbaar in menu" weghaald werkt dit niet. Je moet het eerst een los menu item maken voordat het niet meer zichtbaar wordt.

**Comment by indiePeeters** [comment]
Ik snap niet helemaal wat ik moet testen hier. 

Als het de checkbox "Toon pagina in menu" uitvinkt waneer een pagina een submenu element is verdwijnt hij uit het menu. Dit werk, als je dit bedoeld..

**Comment by wouterbles** [comment]
Raar, dat is niet wat er bij Bjarne en mij gebeurd. Wat gebeurt er bij jou wanneer je het vinkje "toon pagina" weg haalt bij de commissie pagina op de ESAC site?

**Comment by indiePeeters** [comment]
Op de live versie blijft het menu item staan. 

Op de pr versie niet.

**Comment by wouterbles** [comment]
Ahh vandaar! Maar wat jij beschrijft is de bedoeling 👍
