### ISSUE TITLE
Overstappen nieuwe mailserver

### ISSUE THREAD

**Issue by wouterbles** [esac-ic/esac.nl#8]
Mails naar hotmail adressen komen vaak in spam terecht of helemaal niet in.

De IP adressen van Mailgun hebben een te slechte reputatie.

**Comment by wouterbles** [comment]
Update hierover:

- De Mailman 3 server is draaiende op de NSAC webserver
- De API is opgezet en ik heb de inlog gegevens van Richard hiervoor
- De mailserver draait onder het domein esac.alpenclub.nl

Alles staat dus klaar voor het omzetten van de mail omgeving naar mailman. Wanneer een PR zo ver is kan aan de NSAC kant het domein aangepast worden van alpenclub -> esac.nl.

**Comment by nieka** [comment]
Documentaite link: https://mailman.readthedocs.io/en/master/src/mailman/rest/docs/lists.html#paginating-over-list-records
