### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by wouterbles** [esac-ic/esac.nl#81]
Het lijkt me een goed idee om te kijken of we een aantal dependencies willen updaten, oa:

- PHP naar 7.3
- Bootstrap (dit zal ik oppakken)
- Laravel mix

Hoe denken jullie hier over? Niet dat we op dit moment persé nieuwe funcitonaliteiten uit die versies nodig hebben, maar in de toekomst zullen we toch een keer moeten upgraden.

**Comment by marijnvanderhorst** [comment]
We zitten momenteel op Laravel versie 5.5, wat een LTS versie is. Het lijkt me het beste om Laravel pas te updaten zodra er een nieuwe LTS versie uitkomt. Ik verwacht dat dit bij de volgende versie, 5.9, weer het geval zal zijn.

De overige punten lijken me inderdaad goed om een update te geven.

**Comment by wouterbles** [comment]
Mee eens! Dan wachten we nog even met laravel.
